package com.aborayan.matchclock

import android.app.Activity
import android.app.Dialog
import android.content.Intent
import android.content.res.Configuration
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.Drawable
import android.graphics.drawable.GradientDrawable
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.view.WindowInsets
import android.view.WindowManager
import android.widget.*
import org.json.JSONArray
import org.json.JSONObject
import kotlin.math.abs

class SmartRefereeActivity : Activity() {
    private val prefs by lazy { getSharedPreferences("matchclock-state", MODE_PRIVATE) }
    private val states = mutableListOf<MatchState>()
    private val handler = Handler(Looper.getMainLooper())
    private lateinit var root: LinearLayout
    private lateinit var selectorRow: LinearLayout
    private lateinit var contentHost: FrameLayout
    private lateinit var activeChip: TextView
    private var dark = false
    private var showArchived = false
    private var selectedId: Long = -1L
    private var liveTime: TextView? = null
    private var liveLost: TextView? = null
    private var liveShot: TextView? = null
    private var liveStatus: TextView? = null
    private val compact get() = resources.configuration.screenHeightDp < 740 || resources.configuration.screenWidthDp < 360
    private val green = 0xFF168449.toInt()
    private val blue = 0xFF246FB7.toInt()
    private val amber = 0xFFD08B22.toInt()
    private val yellow = 0xFFF3C94B.toInt()
    private val red = 0xFFC94343.toInt()
    private fun bg() = if (dark) 0xFF08120D.toInt() else 0xFFF4F7F4.toInt()
    private fun surface() = if (dark) 0xFF132019.toInt() else Color.WHITE
    private fun surface2() = if (dark) 0xFF1A2B22.toInt() else 0xFFF0F4F1.toInt()
    private fun ink() = if (dark) 0xFFF4F8F5.toInt() else 0xFF132219.toInt()
    private fun muted() = if (dark) 0xFFA8B9AF.toInt() else 0xFF66766C.toInt()
    private fun line() = if (dark) 0xFF35473B.toInt() else 0xFFD9E2DB.toInt()
    private val ticker = object : Runnable { override fun run() { updateLive(); handler.postDelayed(this, 180L) } }

    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); load(); if (selectedId == -1L) selectedId = visibleStates().firstOrNull()?.id ?: -1L; buildUi(); handler.post(ticker) }
    override fun onPause() { save(); super.onPause() }
    override fun onDestroy() { handler.removeCallbacks(ticker); save(); super.onDestroy() }
    override fun onConfigurationChanged(newConfig: Configuration) { super.onConfigurationChanged(newConfig); buildUi() }
    private fun dp(v: Int) = (v * resources.displayMetrics.density + 0.5f).toInt()
    private fun latin(s: String): String = buildString(s.length) { s.forEach { c -> append(when (c) { '٠','۰'->'0';'١','۱'->'1';'٢','۲'->'2';'٣','۳'->'3';'٤','۴'->'4';'٥','۵'->'5';'٦','۶'->'6';'٧','۷'->'7';'٨','۸'->'8';'٩','۹'->'9';else->c }) } }
    private fun shape(color: Int, radius: Int = 16, stroke: Int? = null, strokeWidth: Int = 1) = GradientDrawable().apply { setColor(color); cornerRadius = dp(radius).toFloat(); if (stroke != null) setStroke(dp(strokeWidth), stroke) }
    private fun text(s: String, size: Float = 14f, color: Int = ink(), bold: Boolean = false) = TextView(this).apply { text = latin(s); textSize = size; setTextColor(color); gravity = Gravity.CENTER_VERTICAL; includeFontPadding = false; if (bold) setTypeface(typeface, Typeface.BOLD) }
    private fun drawable(res: Int, tint: Int? = null, size: Int = 24): Drawable? = getDrawable(res)?.mutate()?.also { if (tint != null) it.setTint(tint); it.setBounds(0,0,dp(size),dp(size)) }
    private fun iconButton(res: Int, content: String, tint: Int = ink(), fill: Int = surface2(), size: Int = 46, onClick: () -> Unit) = ImageButton(this).apply { setImageResource(res); drawable?.mutate()?.setTint(tint); background=shape(fill,14,if(fill==surface2()) line() else null); contentDescription=content; scaleType=ImageView.ScaleType.CENTER; setPadding(dp(11),dp(11),dp(11),dp(11)); setOnClickListener{onClick()}; minimumWidth=dp(size);minimumHeight=dp(size) }
    private fun actionButton(label:String,icon:Int,fill:Int,color:Int=Color.WHITE,height:Int=56,onClick:()->Unit)=Button(this).apply{ text=latin(label);isAllCaps=false;textSize=if(compact)13f else 14f;setTextColor(color);setTypeface(typeface,Typeface.BOLD);gravity=Gravity.CENTER;background=shape(fill,16,if(fill==surface2())line()else null);minHeight=dp(height);minimumHeight=dp(height);minimumWidth=0;compoundDrawablePadding=dp(7);setCompoundDrawablesRelative(drawable(icon,color,if(compact)21 else 24),null,null,null);setPadding(dp(8),0,dp(8),0);setOnClickListener{onClick()} }
    private fun row(gap:Int=8)=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;showDividers=LinearLayout.SHOW_DIVIDER_MIDDLE;dividerDrawable=object:android.graphics.drawable.ColorDrawable(Color.TRANSPARENT){override fun getIntrinsicWidth()=dp(gap)}}
    private fun col()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL}
    private fun weight(v:View,w:Float=1f)=v.apply{layoutParams=LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,w)}

    private fun buildUi(){
        window.statusBarColor=bg();window.navigationBarColor=bg();@Suppress("DEPRECATION") window.decorView.systemUiVisibility=if(!dark)View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR else 0
        root=col().apply{layoutDirection=View.LAYOUT_DIRECTION_RTL;setBackgroundColor(bg());setPadding(dp(10),dp(8),dp(10),dp(8))};applyInsets(root)
        root.addView(buildHeader(),LinearLayout.LayoutParams(-1,dp(if(compact)50 else 56)))
        root.addView(buildSelectorBar(),LinearLayout.LayoutParams(-1,dp(if(compact)54 else 62)).apply{topMargin=dp(6)})
        contentHost=FrameLayout(this);root.addView(contentHost,LinearLayout.LayoutParams(-1,0,1f).apply{topMargin=dp(7)})
        setContentView(root);renderSelector();renderActive()
    }
    private fun applyInsets(v:View){v.setOnApplyWindowInsetsListener{view,insets->val l:Int;val t:Int;val r:Int;val b:Int;if(Build.VERSION.SDK_INT>=30){val x=insets.getInsets(WindowInsets.Type.systemBars() or WindowInsets.Type.displayCutout());l=x.left;t=x.top;r=x.right;b=x.bottom}else{@Suppress("DEPRECATION") l=insets.systemWindowInsetLeft;@Suppress("DEPRECATION") t=insets.systemWindowInsetTop;@Suppress("DEPRECATION") r=insets.systemWindowInsetRight;@Suppress("DEPRECATION") b=insets.systemWindowInsetBottom};view.setPadding(dp(10)+l,dp(8)+t,dp(10)+r,dp(8)+b);insets};v.requestApplyInsets()}
    private fun buildHeader():View{val r=row(7);val logo=ImageView(this).apply{setImageResource(R.mipmap.ic_launcher);scaleType=ImageView.ScaleType.FIT_CENTER};r.addView(logo,LinearLayout.LayoutParams(dp(if(compact)42 else 48),dp(if(compact)42 else 48)));val title=col();title.addView(text("ساعات التوقيت",if(compact)18f else 20f,ink(),true));if(!compact)title.addView(text("لوحة تحكيم ذكية",11f,muted()));r.addView(title,LinearLayout.LayoutParams(0,-2,1f));activeChip=text("0 نشطة",11f,green,true).apply{gravity=Gravity.CENTER;background=shape(if(dark)0xFF173725.toInt() else 0xFFE7F5EC.toInt(),99,green);setPadding(dp(9),dp(6),dp(9),dp(6))};r.addView(activeChip);r.addView(iconButton(R.drawable.ic_theme,"الوضع الليلي",size=if(compact)42 else 46){dark=!dark;prefs.edit().putBoolean("dark",dark).apply();buildUi()},LinearLayout.LayoutParams(dp(if(compact)42 else 46),dp(if(compact)42 else 46)));r.addView(iconButton(R.drawable.ic_menu_smart,"القائمة",size=if(compact)42 else 46){showMainMenu()},LinearLayout.LayoutParams(dp(if(compact)42 else 46),dp(if(compact)42 else 46)));return r}
    private fun buildSelectorBar():View{val outer=row(6);val scroll=HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false;overScrollMode=View.OVER_SCROLL_NEVER};selectorRow=row(6).apply{setPadding(dp(2),0,dp(2),0)};scroll.addView(selectorRow,ViewGroup.LayoutParams(-2,-1));outer.addView(scroll,LinearLayout.LayoutParams(0,-1,1f));outer.addView(iconButton(R.drawable.ic_add_smart,"إضافة بطاقة",Color.WHITE,green,if(compact)50 else 56){showAddDialog()},LinearLayout.LayoutParams(dp(if(compact)50 else 56),dp(if(compact)50 else 56)));return outer}
    private fun visibleStates()=states.filter{showArchived||!it.archived}
    private fun renderSelector(){if(!::selectorRow.isInitialized)return;selectorRow.removeAllViews();val list=visibleStates();if(list.isNotEmpty()&&list.none{it.id==selectedId})selectedId=list.first().id;list.forEachIndexed{index,s->val selected=s.id==selectedId;val b=Button(this).apply{isAllCaps=false;text=latin("${index+1}  ${s.title}   ${scoreSummary(s)}");textSize=if(compact)11.5f else 12.5f;setTypeface(typeface,if(selected)Typeface.BOLD else Typeface.NORMAL);setTextColor(if(selected)Color.WHITE else ink());background=shape(if(selected)green else surface(),14,if(selected)green else line());minHeight=dp(if(compact)46 else 52);minimumHeight=dp(if(compact)46 else 52);setPadding(dp(12),0,dp(12),0);setOnClickListener{selectedId=s.id;renderSelector();renderActive()}};selectorRow.addView(b,LinearLayout.LayoutParams(-2,dp(if(compact)46 else 52)))};activeChip.text=latin("${states.count{it.running&&!it.archived}} نشطة")}
    private fun scoreSummary(s:MatchState)=when(s.type){MatchState.TYPE_SHOOTOUT->"${s.kicks.count{it.team=="home"&&it.scored}}:${s.kicks.count{it.team=="away"&&it.scored}}";MatchState.TYPE_SETS->"${s.setsHome}:${s.setsAway}";else->"${s.scoreHome}:${s.scoreAway}"}

    private fun renderActive(){liveTime=null;liveLost=null;liveShot=null;liveStatus=null;contentHost.removeAllViews();val s=visibleStates().firstOrNull{it.id==selectedId};if(s==null){val empty=col().apply{gravity=Gravity.CENTER;background=shape(surface(),22,line());addView(ImageView(this@SmartRefereeActivity).apply{setImageResource(R.mipmap.ic_launcher);alpha=0.8f},LinearLayout.LayoutParams(dp(86),dp(86)));addView(text("ابدأ بإضافة بطاقة مباراة",17f,ink(),true).apply{gravity=Gravity.CENTER;setPadding(0,dp(14),0,dp(5))});addView(text("ستظهر المباراة النشطة هنا كاملة بدون سحب رأسي.",12f,muted()).apply{gravity=Gravity.CENTER})};contentHost.addView(empty,FrameLayout.LayoutParams(-1,-1));return};val panel=when(s.type){MatchState.TYPE_SHOOTOUT->shootoutPanel(s);MatchState.TYPE_SETS->setsPanel(s);MatchState.TYPE_BASKETBALL->basketPanel(s);else->matchPanel(s)};contentHost.addView(panel,FrameLayout.LayoutParams(-1,-1));updateLive()}
    private fun basePanel(s:MatchState)=col().apply{setPadding(dp(if(compact)10 else 14),dp(if(compact)9 else 12),dp(if(compact)10 else 14),dp(if(compact)9 else 12));background=shape(surface(),22,if(s.running)green else line(),if(s.running)2 else 1);elevation=dp(2).toFloat();val h=row(6);val titleBox=col();titleBox.addView(text(s.title,if(compact)16f else 18f,ink(),true));titleBox.addView(text(typeName(s),10.5f,muted(),true));h.addView(titleBox,LinearLayout.LayoutParams(0,-2,1f));liveStatus=text(if(s.running)"● تعمل" else "● متوقفة",11f,if(s.running)green else muted(),true).apply{gravity=Gravity.CENTER};h.addView(liveStatus);h.addView(iconButton(R.drawable.ic_settings_smart,"الإعدادات",size=if(compact)40 else 44){showSettingsDialog(s)},LinearLayout.LayoutParams(dp(if(compact)40 else 44),dp(if(compact)40 else 44)));h.addView(iconButton(R.drawable.ic_delete_smart,"حذف",red,if(dark)0xFF341D1D.toInt() else 0xFFFFEFEF.toInt(),if(compact)40 else 44){showDeleteDialog(s)},LinearLayout.LayoutParams(dp(if(compact)40 else 44),dp(if(compact)40 else 44)));addView(h)}
    private fun typeName(s:MatchState)=when(s.type){MatchState.TYPE_SHOOTOUT->"ضربات ترجيح";MatchState.TYPE_SETS->"أشواط";MatchState.TYPE_BASKETBALL->"كرة سلة";else->if(s.sport=="handball")"كرة يد" else "كرة قدم"}

    private fun matchPanel(s:MatchState):View{val card=basePanel(s);val timerBox=col().apply{gravity=Gravity.CENTER};liveTime=text("00:00.0",if(compact)46f else 58f,ink(),true).apply{gravity=Gravity.CENTER;typeface=Typeface.MONOSPACE};timerBox.addView(liveTime,LinearLayout.LayoutParams(-1,0,1f));liveLost=text("الوقت الضائع 00:00",if(compact)11f else 12.5f,amber,true).apply{gravity=Gravity.CENTER};timerBox.addView(liveLost);card.addView(timerBox,LinearLayout.LayoutParams(-1,0,if(compact)1.15f else 1.25f).apply{topMargin=dp(2)});card.addView(scoreBoard(s),LinearLayout.LayoutParams(-1,dp(if(compact)96 else 108)).apply{topMargin=dp(6)});val controls=row(8);controls.addView(weight(actionButton(if(s.running)"إيقاف" else "ابدأ",if(s.running)R.drawable.ic_pause_smart else R.drawable.ic_play_smart,if(s.running)amber else green,height=if(compact)50 else 56){if(s.running)s.freeze() else s.resume();save();renderActive();renderSelector()}));controls.addView(weight(actionButton("تصفير",R.drawable.ic_reset_smart,surface2(),ink(),if(compact)50 else 56){showResetDialog(s)}));card.addView(controls,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(7)});val ev=row(7);ev.addView(weight(actionButton("هدف",R.drawable.ic_goal,green,Color.WHITE,if(compact)52 else 58){showEventDialog(s,"goal")}));ev.addView(weight(actionButton("إنذار",R.drawable.ic_yellow_card_smart,yellow,0xFF302814.toInt(),if(compact)52 else 58){showEventDialog(s,"yellow")}));ev.addView(weight(actionButton("طرد",R.drawable.ic_red_card_smart,red,Color.WHITE,if(compact)52 else 58){showEventDialog(s,"red")}));card.addView(ev,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(7)});card.addView(recentEventsBox(s),LinearLayout.LayoutParams(-1,0,if(compact) 0.75f else 0.9f).apply{topMargin=dp(7)});val bottom=row(6);bottom.addView(weight(actionButton("السجل",R.drawable.ic_list_smart,surface2(),ink(),if(compact)44 else 48){showLogDialog(s)}));bottom.addView(weight(actionButton("تقرير",R.drawable.ic_report_smart,surface2(),ink(),if(compact)44 else 48){shareReport(s)}));bottom.addView(weight(actionButton("تكبير",R.drawable.ic_fullscreen,surface2(),ink(),if(compact)44 else 48){bigScreen(s)}));card.addView(bottom,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(7)});return card}
    private fun scoreBoard(s:MatchState):View{val outer=row(7).apply{setPadding(dp(6),dp(6),dp(6),dp(6));background=shape(surface2(),18)};outer.addView(weight(teamScoreBox(s,true)));outer.addView(text(":",30f,muted(),true).apply{gravity=Gravity.CENTER;setPadding(dp(4),0,dp(4),0)});outer.addView(weight(teamScoreBox(s,false)));return outer}
    private fun teamScoreBox(s:MatchState,home:Boolean):View{val box=col().apply{gravity=Gravity.CENTER};box.addView(text(if(home)s.home else s.away,if(compact)12f else 13.5f,ink(),true).apply{gravity=Gravity.CENTER;maxLines=1});val r=row(5);r.gravity=Gravity.CENTER;r.addView(iconButton(R.drawable.ic_minus_smart,"إنقاص",ink(),surface(),if(compact)38 else 44){if(home)s.scoreHome=(s.scoreHome-1).coerceAtLeast(0) else s.scoreAway=(s.scoreAway-1).coerceAtLeast(0);save();renderActive();renderSelector()},LinearLayout.LayoutParams(dp(if(compact)38 else 44),dp(if(compact)38 else 44)));r.addView(text((if(home)s.scoreHome else s.scoreAway).toString(),if(compact)28f else 34f,ink(),true).apply{gravity=Gravity.CENTER;typeface=Typeface.MONOSPACE;minWidth=dp(if(compact)44 else 54)});r.addView(iconButton(R.drawable.ic_add_smart,"زيادة",Color.WHITE,if(home)green else blue,if(compact)38 else 44){if(home)s.scoreHome++ else s.scoreAway++;save();renderActive();renderSelector()},LinearLayout.LayoutParams(dp(if(compact)38 else 44),dp(if(compact)38 else 44)));box.addView(r,LinearLayout.LayoutParams(-1,0,1f));return box}
    private fun recentEventsBox(s:MatchState):View{val box=col().apply{setPadding(dp(9),dp(6),dp(9),dp(6));background=shape(if(dark)0xFF101B15.toInt() else 0xFFFAFCFA.toInt(),15,line())};val head=row(5);head.addView(text("آخر الأحداث",12f,ink(),true),LinearLayout.LayoutParams(0,-2,1f));head.addView(text("${s.events.size} حدث",10.5f,muted(),true));box.addView(head);val take=if(compact)1 else 2;if(s.events.isEmpty())box.addView(text("لا توجد أحداث مسجلة",11f,muted()).apply{gravity=Gravity.CENTER},LinearLayout.LayoutParams(-1,0,1f))else s.events.takeLast(take).asReversed().forEach{box.addView(eventMiniRow(s,it),LinearLayout.LayoutParams(-1,0,1f))};return box}
    private fun eventMiniRow(s:MatchState,e:MatchEvent):View{val r=row(6);val icon=ImageView(this).apply{setImageResource(eventIcon(e.kind));drawable?.mutate()?.setTint(eventColor(e.kind));scaleType=ImageView.ScaleType.CENTER;setPadding(dp(5),dp(5),dp(5),dp(5))};r.addView(icon,LinearLayout.LayoutParams(dp(32),dp(32)));val label="${eventName(e.kind)} • ${if(e.team=="home")s.home else s.away}";val person=if(e.player.isNotBlank()||e.number.isNotBlank())"#${e.number.ifBlank{"-"}}  ${e.player.ifBlank{"بدون اسم"}}" else "بدون بيانات لاعب";val c=col();c.addView(text(label,10.5f,ink(),true));c.addView(text(person,10f,muted()));r.addView(c,LinearLayout.LayoutParams(0,-2,1f));r.addView(text(clock(e.timeMs),10.5f,muted(),true).apply{gravity=Gravity.CENTER});return r}

    private fun showEventDialog(s:MatchState,kind:String){val d=styledDialog(eventName(kind),eventIcon(kind),eventColor(kind));val body=d.second;var team="home";val teamRow=row(7);val homeBtn=Button(this);val awayBtn=Button(this);fun styleTeam(){listOf(homeBtn to "home",awayBtn to "away").forEach{(b,key)->b.isAllCaps=false;b.textSize=13f;b.setTypeface(b.typeface,Typeface.BOLD);b.setTextColor(if(team==key)Color.WHITE else ink());b.background=shape(if(team==key)(if(key=="home")green else blue)else surface2(),14,if(team==key)null else line());b.minHeight=dp(50);b.minimumHeight=dp(50)}};homeBtn.text=latin(s.home);awayBtn.text=latin(s.away);homeBtn.setOnClickListener{team="home";styleTeam()};awayBtn.setOnClickListener{team="away";styleTeam()};styleTeam();teamRow.addView(weight(homeBtn));teamRow.addView(weight(awayBtn));body.addView(teamRow);val player=input("اسم اللاعب",InputType.TYPE_CLASS_TEXT);val number=input("رقم اللاعب",InputType.TYPE_CLASS_NUMBER).apply{textDirection=View.TEXT_DIRECTION_LTR};body.addView(labeledField("اسم اللاعب",player));body.addView(labeledField("رقم اللاعب",number));val error=text("",10.5f,red,true).apply{visibility=View.GONE};body.addView(error);body.addView(dialogButtons("تسجيل",eventColor(kind),R.drawable.ic_check_smart,"إلغاء",{val name=player.text.toString().trim();val no=latin(number.text.toString().trim());if(name.isBlank()||no.isBlank()){error.text="أدخل اسم اللاعب ورقمه قبل تسجيل الحدث";error.visibility=View.VISIBLE}else{if(s.autoPause&&s.running)s.freeze();if(kind=="goal"){if(team=="home")s.scoreHome++ else s.scoreAway++};s.events.add(MatchEvent(s.currentElapsed(),kind,team,name,no));save();d.first.dismiss();renderActive();renderSelector()}},{d.first.dismiss()}));d.first.show();fitDialog(d.first)}
    private fun showLogDialog(s:MatchState){val d=styledDialog("سجل أحداث المباراة",R.drawable.ic_list_smart,green);val body=d.second;val scroll=ScrollView(this).apply{isFillViewport=true};val list=col();if(s.events.isEmpty())list.addView(text("لا توجد أحداث حتى الآن",13f,muted()).apply{gravity=Gravity.CENTER;setPadding(0,dp(30),0,dp(30))})else s.events.asReversed().forEach{e->val r=eventMiniRow(s,e).apply{setPadding(dp(8),dp(7),dp(8),dp(7));background=shape(surface2(),13,line())};list.addView(r,LinearLayout.LayoutParams(-1,dp(58)).apply{bottomMargin=dp(6)})};scroll.addView(list);body.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));val tools=row(7);tools.addView(weight(actionButton("تراجع آخر حدث",R.drawable.ic_undo_smart,surface2(),ink(),48){if(s.events.isNotEmpty()){val e=s.events.removeAt(s.events.lastIndex);if(e.kind=="goal"){if(e.team=="home")s.scoreHome=(s.scoreHome-1).coerceAtLeast(0) else s.scoreAway=(s.scoreAway-1).coerceAtLeast(0)};save();d.first.dismiss();renderActive();renderSelector()}}));tools.addView(weight(actionButton("إغلاق",R.drawable.ic_close_smart,green,Color.WHITE,48){d.first.dismiss()}));body.addView(tools);d.first.show();fitDialog(d.first,0.92f,0.86f)}

    private fun shootoutPanel(s:MatchState):View{val card=basePanel(s);val hs=s.kicks.count{it.team=="home"&&it.scored};val ascore=s.kicks.count{it.team=="away"&&it.scored};val center=col().apply{gravity=Gravity.CENTER};center.addView(text("$hs : $ascore",if(compact)48f else 62f,ink(),true).apply{gravity=Gravity.CENTER;typeface=Typeface.MONOSPACE});center.addView(text("${s.home}     •     ${s.away}",14f,muted(),true).apply{gravity=Gravity.CENTER});center.addView(text("${kickTrack(s,"home")}     ${kickTrack(s,"away")}",14f,muted(),true).apply{gravity=Gravity.CENTER});card.addView(center,LinearLayout.LayoutParams(-1,0,1.5f));val winner=shootoutWinner(s);if(winner!=null)card.addView(text("الفائز: ${if(winner=="home")s.home else s.away}",16f,green,true).apply{gravity=Gravity.CENTER});val main=row(8);if(s.kickOrder.isBlank()){main.addView(weight(actionButton("${s.home} يبدأ",R.drawable.ic_play_smart,green){s.kickOrder="home";save();renderActive()}));main.addView(weight(actionButton("${s.away} يبدأ",R.drawable.ic_play_smart,blue){s.kickOrder="away";save();renderActive()}))}else if(winner==null){main.addView(weight(actionButton("هدف",R.drawable.ic_goal,green){s.kicks.add(Kick(currentKicker(s),true));save();renderActive();renderSelector()}));main.addView(weight(actionButton("إهدار",R.drawable.ic_close_smart,red){s.kicks.add(Kick(currentKicker(s),false));save();renderActive();renderSelector()}))};card.addView(main);val tools=row(8);tools.addView(weight(actionButton("تراجع",R.drawable.ic_undo_smart,surface2(),ink(),50){if(s.kicks.isNotEmpty())s.kicks.removeAt(s.kicks.lastIndex);save();renderActive();renderSelector()}));tools.addView(weight(actionButton("تصفير",R.drawable.ic_reset_smart,surface2(),red,50){s.kicks.clear();s.kickOrder="";save();renderActive();renderSelector()}));card.addView(tools,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)});card.addView(commonBottom(s),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)});return card}
    private fun setsPanel(s:MatchState):View{val card=basePanel(s);val finished=s.setsHome>=s.setsToWin||s.setsAway>=s.setsToWin;val center=col().apply{gravity=Gravity.CENTER};center.addView(text("${s.setPointsHome} : ${s.setPointsAway}",if(compact)52f else 64f,ink(),true).apply{gravity=Gravity.CENTER;typeface=Typeface.MONOSPACE});center.addView(text("الأشواط  ${s.setsHome} : ${s.setsAway}",16f,muted(),true).apply{gravity=Gravity.CENTER});if(finished)center.addView(text("الفائز: ${if(s.setsHome>s.setsAway)s.home else s.away}",15f,green,true).apply{gravity=Gravity.CENTER});card.addView(center,LinearLayout.LayoutParams(-1,0,1.5f));if(!finished){val add=row(8);add.addView(weight(actionButton("+ ${s.home}",R.drawable.ic_add_smart,green){addSetPoint(s,"home")}));add.addView(weight(actionButton("+ ${s.away}",R.drawable.ic_add_smart,blue){addSetPoint(s,"away")}));card.addView(add)};val tools=row(8);tools.addView(weight(actionButton("تراجع",R.drawable.ic_undo_smart,surface2(),ink(),50){undoSetPoint(s)}));tools.addView(weight(actionButton("تصفير",R.drawable.ic_reset_smart,surface2(),red,50){s.setPointsHome=0;s.setPointsAway=0;s.setsHome=0;s.setsAway=0;s.setHistory.clear();s.pointHistory.clear();save();renderActive();renderSelector()}));card.addView(tools,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)});card.addView(commonBottom(s),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)});return card}
    private fun basketPanel(s:MatchState):View{val card=basePanel(s);val top=row(8);top.addView(text(if(s.quarter<=4)"الربع ${s.quarter}" else "إضافي ${s.quarter-4}",13f,muted(),true),LinearLayout.LayoutParams(0,-2,1f));liveShot=text("24",14f,amber,true).apply{gravity=Gravity.CENTER;background=shape(surface2(),99,line());setPadding(dp(12),dp(6),dp(12),dp(6))};top.addView(liveShot);card.addView(top);liveTime=text("10:00",if(compact)46f else 58f,ink(),true).apply{gravity=Gravity.CENTER;typeface=Typeface.MONOSPACE};card.addView(liveTime,LinearLayout.LayoutParams(-1,0,0.9f));card.addView(scoreBoard(s),LinearLayout.LayoutParams(-1,dp(if(compact)92 else 104)));val ctl=row(8);ctl.addView(weight(actionButton(if(s.running)"إيقاف" else "ابدأ",if(s.running)R.drawable.ic_pause_smart else R.drawable.ic_play_smart,if(s.running)amber else green,height=50){if(s.running)s.freeze() else if(s.basketballRemaining()>0)s.resume();save();renderActive()}));ctl.addView(weight(actionButton("24 ثانية",R.drawable.ic_reset_smart,surface2(),amber,50){resetShot(s);save();renderActive()}));card.addView(ctl,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(6)});val pts1=row(5);for(p in 1..3)pts1.addView(weight(actionButton("+$p ${s.home}",R.drawable.ic_add_smart,surface2(),green,44){addBasket(s,"home",p)}));card.addView(pts1,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(5)});val pts2=row(5);for(p in 1..3)pts2.addView(weight(actionButton("+$p ${s.away}",R.drawable.ic_add_smart,surface2(),blue,44){addBasket(s,"away",p)}));card.addView(pts2,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(5)});val tools=row(6);tools.addView(weight(actionButton("خطأ ${s.home}: ${s.foulsHome}",R.drawable.ic_yellow_card_smart,surface2(),if(s.foulsHome>=5)red else ink(),44){s.foulsHome++;save();renderActive()}));tools.addView(weight(actionButton("خطأ ${s.away}: ${s.foulsAway}",R.drawable.ic_yellow_card_smart,surface2(),if(s.foulsAway>=5)red else ink(),44){s.foulsAway++;save();renderActive()}));card.addView(tools,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(5)});card.addView(commonBottom(s),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(6)});return card}
    private fun commonBottom(s:MatchState):View{val r=row(6);r.addView(weight(actionButton("تقرير",R.drawable.ic_report_smart,surface2(),ink(),46){shareReport(s)}));r.addView(weight(actionButton("تكبير",R.drawable.ic_fullscreen,surface2(),ink(),46){bigScreen(s)}));r.addView(weight(actionButton(if(s.archived)"استعادة" else "أرشفة",R.drawable.ic_archive,surface2(),if(s.archived)green else muted(),46){if(s.running)s.freeze();s.archived=!s.archived;save();if(s.archived)selectedId=visibleStates().firstOrNull()?.id?:-1;renderSelector();renderActive()}));return r}

    private fun styledDialog(title:String,iconRes:Int,iconColor:Int):Pair<Dialog,LinearLayout>{val d=Dialog(this);d.window?.requestFeature(android.view.Window.FEATURE_NO_TITLE);val r=col().apply{setPadding(dp(18),dp(16),dp(18),dp(16));background=shape(surface(),24);layoutDirection=View.LAYOUT_DIRECTION_RTL};val head=row(9);val icon=ImageView(this).apply{setImageResource(iconRes);drawable?.mutate()?.setTint(iconColor);background=shape(if(dark)0xFF183126.toInt() else 0xFFEAF4ED.toInt(),16);setPadding(dp(10),dp(10),dp(10),dp(10))};head.addView(icon,LinearLayout.LayoutParams(dp(46),dp(46)));head.addView(text(title,18f,ink(),true),LinearLayout.LayoutParams(0,-2,1f));head.addView(iconButton(R.drawable.ic_close_smart,"إغلاق",ink(),surface2(),40){d.dismiss()},LinearLayout.LayoutParams(dp(40),dp(40)));r.addView(head);val body=col().apply{setPadding(0,dp(12),0,0)};r.addView(body,LinearLayout.LayoutParams(-1,0,1f));d.setContentView(r);return d to body}
    private fun fitDialog(d:Dialog,width:Float=0.92f,height:Float=0.74f){d.window?.let{w->val dm=resources.displayMetrics;w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout((dm.widthPixels*width).toInt(),(dm.heightPixels*height).toInt());w.setDimAmount(0.48f);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND)}}
    private fun input(hint:String,type:Int)=EditText(this).apply{this.hint=hint;inputType=type;setTextColor(ink());setHintTextColor(muted());textSize=14f;background=shape(surface2(),13,line());setPadding(dp(12),0,dp(12),0);isSingleLine=true;layoutDirection=View.LAYOUT_DIRECTION_RTL}
    private fun labeledField(label:String,field:EditText):View=col().apply{addView(text(label,11f,muted(),true),LinearLayout.LayoutParams(-1,dp(24)));addView(field,LinearLayout.LayoutParams(-1,dp(50)));setPadding(0,dp(5),0,0)}
    private fun dialogButtons(ok:String,okColor:Int,okIcon:Int,cancel:String,onOk:()->Unit,onCancel:()->Unit):View{val r=row(7).apply{setPadding(0,dp(10),0,0)};r.addView(weight(actionButton(ok,okIcon,okColor,Color.WHITE,50,onOk)));r.addView(weight(actionButton(cancel,R.drawable.ic_close_smart,surface2(),ink(),50,onCancel)));return r}
    private fun showAddDialog(){val d=styledDialog("بطاقة جديدة",R.drawable.ic_add_smart,green);val body=d.second;val grid=GridLayout(this).apply{columnCount=2;alignmentMode=GridLayout.ALIGN_BOUNDS};val types=listOf(Triple("ساعة مباراة",R.drawable.ic_goal,MatchState.TYPE_MATCH),Triple("ضربات ترجيح",R.drawable.ic_goal,MatchState.TYPE_SHOOTOUT),Triple("أشواط",R.drawable.ic_card,MatchState.TYPE_SETS),Triple("كرة سلة",R.drawable.ic_card,MatchState.TYPE_BASKETBALL));types.forEach{(label,icon,type)->val b=actionButton(label,icon,surface2(),ink(),70){val title=when(type){MatchState.TYPE_SHOOTOUT->"ضربات ترجيح";MatchState.TYPE_SETS->"مباراة أشواط";MatchState.TYPE_BASKETBALL->"كرة السلة";else->"المباراة ${states.size+1}"};val s=MatchState(type=type,title=title,home="الفريق 1",away="الفريق 2");states.add(s);selectedId=s.id;save();d.first.dismiss();renderSelector();renderActive()};val lp=GridLayout.LayoutParams().apply{width=0;height=dp(78);columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1,1f);setMargins(dp(4),dp(4),dp(4),dp(4))};grid.addView(b,lp)};body.addView(grid,LinearLayout.LayoutParams(-1,-1));d.first.show();fitDialog(d.first,0.92f,0.48f)}
    private fun showMainMenu(){val d=styledDialog("القائمة",R.drawable.ic_menu_smart,green);val body=d.second;val grid=GridLayout(this).apply{columnCount=2};fun add(label:String,icon:Int,action:()->Unit){val b=actionButton(label,icon,surface2(),ink(),64){action();d.first.dismiss()};val lp=GridLayout.LayoutParams().apply{width=0;height=dp(72);columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1,1f);setMargins(dp(4),dp(4),dp(4),dp(4))};grid.addView(b,lp)};add("إضافة بطاقة",R.drawable.ic_add_smart){showAddDialog()};add(if(showArchived)"إخفاء الأرشيف" else "عرض الأرشيف",R.drawable.ic_archive){showArchived=!showArchived;renderSelector();renderActive()};add("تصدير نسخة",R.drawable.ic_report_smart){exportBackup()};add("استيراد نسخة",R.drawable.ic_list_smart){importBackup()};body.addView(grid,LinearLayout.LayoutParams(-1,-1));d.first.show();fitDialog(d.first,0.92f,0.48f)}
    private fun showSettingsDialog(s:MatchState){val d=styledDialog("إعدادات البطاقة",R.drawable.ic_settings_smart,green);val body=d.second;val title=input("اسم البطاقة",InputType.TYPE_CLASS_TEXT).apply{setText(s.title)};val home=input("الفريق 1",InputType.TYPE_CLASS_TEXT).apply{setText(s.home)};val away=input("الفريق 2",InputType.TYPE_CLASS_TEXT).apply{setText(s.away)};body.addView(labeledField("اسم البطاقة",title));body.addView(labeledField("الفريق الأول",home));body.addView(labeledField("الفريق الثاني",away));var extra:EditText?=null;if(s.type==MatchState.TYPE_MATCH||s.type==MatchState.TYPE_BASKETBALL||s.type==MatchState.TYPE_SETS){extra=input("القيمة",InputType.TYPE_CLASS_NUMBER).apply{setText(when(s.type){MatchState.TYPE_MATCH->s.halfMinutes;MatchState.TYPE_BASKETBALL->s.quarterMinutes;else->s.pointsPerSet}.toString())};body.addView(labeledField(when(s.type){MatchState.TYPE_MATCH->"مدة الشوط بالدقائق";MatchState.TYPE_BASKETBALL->"مدة الربع بالدقائق";else->"نقاط الشوط"},extra))};body.addView(dialogButtons("حفظ",green,R.drawable.ic_check_smart,"إلغاء",{s.title=title.text.toString().trim().ifBlank{s.title};s.home=home.text.toString().trim().ifBlank{"الفريق 1"};s.away=away.text.toString().trim().ifBlank{"الفريق 2"};val v=extra?.text?.toString()?.toIntOrNull();if(v!=null)when(s.type){MatchState.TYPE_MATCH->s.halfMinutes=v.coerceIn(1,200);MatchState.TYPE_BASKETBALL->s.quarterMinutes=v.coerceIn(1,30);MatchState.TYPE_SETS->s.pointsPerSet=v.coerceIn(1,100)};save();d.first.dismiss();renderSelector();renderActive()},{d.first.dismiss()}));d.first.show();fitDialog(d.first,0.92f,if(extra==null) 0.62f else 0.72f)}
    private fun showDeleteDialog(s:MatchState){val d=styledDialog("حذف البطاقة",R.drawable.ic_delete_smart,red);val body=d.second;body.addView(text("سيتم حذف «${s.title}» وجميع بياناتها نهائيًا.",13f,muted()).apply{gravity=Gravity.CENTER;setPadding(0,dp(18),0,dp(18))},LinearLayout.LayoutParams(-1,0,1f));body.addView(dialogButtons("حذف",red,R.drawable.ic_delete_smart,"إلغاء",{states.remove(s);selectedId=visibleStates().firstOrNull()?.id?:-1;save();d.first.dismiss();renderSelector();renderActive()},{d.first.dismiss()}));d.first.show();fitDialog(d.first,0.9f,0.4f)}
    private fun showResetDialog(s:MatchState){val d=styledDialog("تصفير المباراة",R.drawable.ic_reset_smart,amber);val body=d.second;body.addView(text("سيتم تصفير الوقت والنتيجة والسجل لهذه المباراة.",13f,muted()).apply{gravity=Gravity.CENTER;setPadding(0,dp(18),0,dp(18))},LinearLayout.LayoutParams(-1,0,1f));body.addView(dialogButtons("تصفير",amber,R.drawable.ic_reset_smart,"إلغاء",{s.running=false;s.startedAt=0;s.elapsedMs=0;s.lostMs=0;s.pausedAt=0;s.scoreHome=0;s.scoreAway=0;s.events.clear();save();d.first.dismiss();renderActive();renderSelector()},{d.first.dismiss()}));d.first.show();fitDialog(d.first,0.9f,0.4f)}
    private fun eventName(kind:String)=when(kind){"goal"->"هدف";"yellow"->"إنذار";"red"->"طرد";"suspension"->"إيقاف دقيقتين";else->kind}
    private fun eventColor(kind:String)=when(kind){"goal"->green;"yellow"->yellow;"red"->red;else->amber}
    private fun eventIcon(kind:String)=when(kind){"goal"->R.drawable.ic_goal;"yellow"->R.drawable.ic_yellow_card_smart;"red"->R.drawable.ic_red_card_smart;else->R.drawable.ic_yellow_card_smart}

    private fun updateLive(){val s=visibleStates().firstOrNull{it.id==selectedId}?:return;val now=System.currentTimeMillis();when(s.type){MatchState.TYPE_MATCH->{liveTime?.text=clock(s.currentElapsed(now),true);liveLost?.text=latin("الوقت الضائع ${clock(s.currentLost(now))}")};MatchState.TYPE_BASKETBALL->{val remain=s.basketballRemaining(now);liveTime?.text=clock(remain);val shot=((s.shotRemaining(now)+999)/1000).toInt();liveShot?.text=shot.toString();liveShot?.setTextColor(if(shot<=5)red else amber);if(s.running&&remain<=0){s.freeze(now);save();renderActive()}}};liveStatus?.text=if(s.running)"● تعمل" else "● متوقفة";liveStatus?.setTextColor(if(s.running)green else muted());activeChip.text=latin("${states.count{it.running&&!it.archived}} نشطة");if(states.any{it.running&&!it.archived})window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)else window.clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)}
    private fun clock(ms:Long,tenth:Boolean=false):String{val safe=ms.coerceAtLeast(0);val total=safe/1000;val m=total/60;val sec=total%60;return if(tenth)"%02d:%02d.%d".format(m,sec,(safe%1000)/100) else "%02d:%02d".format(m,sec)}
    private fun kickTrack(s:MatchState,team:String)=s.kicks.filter{it.team==team}.joinToString(" "){if(it.scored)"●" else "×"}.ifBlank{"○ ○ ○ ○ ○"}
    private fun currentKicker(s:MatchState):String{val first=if(s.kickOrder.isBlank())"home" else s.kickOrder;val second=if(first=="home")"away" else "home";return if(s.kicks.size%2==0)first else second}
    private fun shootoutWinner(s:MatchState):String?{val hs=s.kicks.count{it.team=="home"&&it.scored};val ascore=s.kicks.count{it.team=="away"&&it.scored};val ht=s.kicks.count{it.team=="home"};val at=s.kicks.count{it.team=="away"};if(ht<5||at<5){if(hs>ascore+(5-at))return"home";if(ascore>hs+(5-ht))return"away";return null};return if(ht==at&&hs!=ascore)if(hs>ascore)"home" else "away" else null}
    private fun addSetPoint(s:MatchState,team:String){s.pointHistory.add(team);if(team=="home")s.setPointsHome++ else s.setPointsAway++;val setNo=s.setsHome+s.setsAway+1;val target=if(setNo>=s.setsToWin*2-1)s.decidingPoints else s.pointsPerSet;if(maxOf(s.setPointsHome,s.setPointsAway)>=target&&abs(s.setPointsHome-s.setPointsAway)>=2){s.setHistory.add(SetResult(s.setPointsHome,s.setPointsAway));if(s.setPointsHome>s.setPointsAway)s.setsHome++ else s.setsAway++;s.setPointsHome=0;s.setPointsAway=0;s.pointHistory.clear()};save();renderActive();renderSelector()}
    private fun undoSetPoint(s:MatchState){if(s.pointHistory.isEmpty())return;val last=s.pointHistory.removeAt(s.pointHistory.lastIndex);if(last=="home")s.setPointsHome=(s.setPointsHome-1).coerceAtLeast(0)else s.setPointsAway=(s.setPointsAway-1).coerceAtLeast(0);save();renderActive()}
    private fun resetShot(s:MatchState){s.shotElapsedMs=0;s.shotStartedAt=if(s.running)System.currentTimeMillis()else 0}
    private fun addBasket(s:MatchState,team:String,p:Int){if(team=="home")s.scoreHome+=p else s.scoreAway+=p;s.basketHistory.add("$team:$p");resetShot(s);save();renderActive();renderSelector()}
    private fun report(s:MatchState)=buildString{appendLine(s.title);appendLine("${s.home} ${s.scoreHome} - ${s.scoreAway} ${s.away}");when(s.type){MatchState.TYPE_MATCH->{appendLine("الوقت: ${clock(s.currentElapsed())}");appendLine("الوقت الضائع: ${clock(s.currentLost())}");s.events.forEach{appendLine("${clock(it.timeMs)} | ${eventName(it.kind)} | ${if(it.team=="home")s.home else s.away} | #${it.number} ${it.player}")}};MatchState.TYPE_SHOOTOUT->appendLine("الترجيح: ${s.kicks.count{it.team=="home"&&it.scored}} - ${s.kicks.count{it.team=="away"&&it.scored}}");MatchState.TYPE_SETS->appendLine("الأشواط: ${s.setsHome} - ${s.setsAway}");MatchState.TYPE_BASKETBALL->appendLine("الربع: ${s.quarter} | الأخطاء: ${s.foulsHome} - ${s.foulsAway}")}}
    private fun shareReport(s:MatchState){startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type="text/plain";putExtra(Intent.EXTRA_TEXT,latin(report(s)));putExtra(Intent.EXTRA_SUBJECT,s.title)},"مشاركة التقرير"))}
    private fun bigScreen(s:MatchState){val d=Dialog(this,android.R.style.Theme_Black_NoTitleBar_Fullscreen);val box=col().apply{gravity=Gravity.CENTER;setPadding(dp(22),dp(22),dp(22),dp(22));setBackgroundColor(0xFF050806.toInt())};box.addView(actionButton("إغلاق",R.drawable.ic_close_smart,0xFF242B27.toInt(),Color.WHITE,48){d.dismiss()},LinearLayout.LayoutParams(-1,dp(48)));box.addView(text("${s.home}        ${s.away}",22f,Color.WHITE,true).apply{gravity=Gravity.CENTER},LinearLayout.LayoutParams(-1,0,0.7f));val t=text("",72f,Color.WHITE,true).apply{gravity=Gravity.CENTER;typeface=Typeface.MONOSPACE};box.addView(t,LinearLayout.LayoutParams(-1,0,1.2f));val sc=text("",60f,Color.WHITE,true).apply{gravity=Gravity.CENTER;typeface=Typeface.MONOSPACE};box.addView(sc,LinearLayout.LayoutParams(-1,0,1f));val up=object:Runnable{override fun run(){if(!d.isShowing)return;t.text=when(s.type){MatchState.TYPE_MATCH->clock(s.currentElapsed());MatchState.TYPE_BASKETBALL->clock(s.basketballRemaining());MatchState.TYPE_SETS->"${s.setsHome} - ${s.setsAway}";else->""};sc.text=when(s.type){MatchState.TYPE_SHOOTOUT->"${s.kicks.count{it.team=="home"&&it.scored}} : ${s.kicks.count{it.team=="away"&&it.scored}}";MatchState.TYPE_SETS->"${s.setPointsHome} : ${s.setPointsAway}";else->"${s.scoreHome} : ${s.scoreAway}"};handler.postDelayed(this,250)}};d.setContentView(box);d.setOnDismissListener{handler.removeCallbacks(up)};d.show();handler.post(up)}
    private fun save(){try{val obj=JSONObject().apply{put("selectedId",selectedId);put("items",JSONArray().apply{states.forEach{put(it.toJson())}})};prefs.edit().putString("json",obj.toString()).putBoolean("dark",dark).apply()}catch(_:Exception){}}
    private fun load(){dark=prefs.getBoolean("dark",false);val raw=prefs.getString("json",null)?:return;try{val obj=JSONObject(raw);selectedId=obj.optLong("selectedId",-1);val arr=obj.optJSONArray("items")?:return;for(i in 0 until arr.length())states.add(MatchState.fromJson(arr.getJSONObject(i)))}catch(_:Exception){states.clear()}}
    private fun backup()=JSONObject().apply{put("app","MatchClock");put("version","1.2.0");put("items",JSONArray().apply{states.forEach{put(it.toJson())}})}.toString(2)
    private fun exportBackup(){startActivityForResult(Intent(Intent.ACTION_CREATE_DOCUMENT).apply{addCategory(Intent.CATEGORY_OPENABLE);type="application/json";putExtra(Intent.EXTRA_TITLE,"matchclock-backup.json")},501)}
    private fun importBackup(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{addCategory(Intent.CATEGORY_OPENABLE);type="application/json"},502)}
    @Deprecated("Compatibility") override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(resultCode!=RESULT_OK)return;val uri=data?.data?:return;try{if(requestCode==501){contentResolver.openOutputStream(uri)?.bufferedWriter()?.use{it.write(backup())};Toast.makeText(this,"تم تصدير النسخة الاحتياطية",Toast.LENGTH_SHORT).show()}else if(requestCode==502){val raw=contentResolver.openInputStream(uri)?.bufferedReader()?.use{it.readText()}?:return;val arr=JSONObject(raw).optJSONArray("items")?:return;states.clear();for(i in 0 until arr.length())states.add(MatchState.fromJson(arr.getJSONObject(i)));selectedId=states.firstOrNull()?.id?:-1;save();renderSelector();renderActive();Toast.makeText(this,"تم الاستيراد",Toast.LENGTH_SHORT).show()}}catch(_:Exception){Toast.makeText(this,"تعذر قراءة الملف",Toast.LENGTH_LONG).show()}}
}
